name: Build, Push & SES Notify

on:
  push:
    branches:
      - main
  pull_request:
  
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Dockerfile to workspace
        run: |
          cat <<EOF > Dockerfile
          FROM python:3.11-slim

          WORKDIR /app

          COPY requirements.txt requirements.txt
          RUN pip install --no-cache-dir -r requirements.txt

          COPY . .

          EXPOSE 5000

          CMD ["python", "app.py"]
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
      
      - name: Image digest
        run: docker images

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # IMPORTANT: Replace 'YOUR_IAM_ROLE_ARN_GOES_HERE' with the actual ARN of your IAM role from AWS!
          role-to-assume: arn:aws:iam::760715349705:role/poda-thendi
          # This must be the AWS region where your SES sender identity is verified.
          aws-region: us-east-1 # Example: us-east-1

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add Dockerfile to workspace
        run: |
          cat <<EOF > Dockerfile
          FROM python:3.11-slim

          WORKDIR /app

          COPY requirements.txt requirements.txt
          RUN pip install --no-cache-dir -r requirements.txt

          COPY . .

          EXPOSE 5000

          CMD ["python", "app.py"]
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

  ses-notification:
    needs: [build, push]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Email Notification (on success)
        if: success()
        run: |
          aws ses send-email \
            --from 'akr813703@gmail.com' \
            --destination 'ToAddresses="akr8137035@gmail.com"' \
            --message 'Subject={Data="✅ Build Success - ${{ github.repository }}"},Body={Text={Data="Build for ${{ github.repository }} on branch `${{ github.ref_name}}` was successful!\n\nCommit: `${{ github.sha}}`\nWorkflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region us-east-1 # Ensure this matches your aws-region above

      - name: Send Email Notification (on failure)
        if: failure()
        run: |
          aws ses send-email \
            --from 'akr813703@gmail.com' \
            --destination 'ToAddresses="akr8137035@gmail.com"' \
            --message 'Subject={Data="❌ Build FAILED - ${{ github.repository }}"},Body={Text={Data="*ALERT:* Build for ${{ github.repository }} on branch `${{ github.ref_name}}` *FAILED!*\n\nCommit: `${{ github.sha}}`\n*Please review logs:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region us-east-1
